### ISSUE TITLE
[Feature request] 添加对使用sharedUserId的应用的支持

### ISSUE THREAD

**Issue by hex3c** [LSPosed/CorePatch#22]
对于使用sharedUserId的应用(例如com.termux)，当安装签名不同的apk时会显示
```
Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package com.termux has a signing lineage that diverges from the lineage of the sharedUserId]
```
而且即使只安装了一个app的情况下，只要使用了sharedUserID，也无法安装不同签名的app，应该是和普通app的检测途径不同(覆盖安装普通app只检查自己的签名)

**Comment by yujincheng08** [comment]
这不是系统的限制吗？我们能干啥

**Comment by laggardkernel** [comment]
不大懂，只是觉的都是安装的时候报错，也许核心破解能够绕过这个限制。

https://www.reddit.com/r/termux/comments/uonv9s/install_failed_shared_user_incompatible/
