### ISSUE TITLE
[BUG] Disable compare signatures doesn't work

### ISSUE THREAD

**Issue by KarmaMod** [LSPosed/CorePatch#26]
**什么情况/What happened?**

Disable compare signatures doesn't work even it's enabled. The package installer still says "app not installed" when installing and overwriting an app with different signature
Installing unsigned APK from forum sites works fine

**LSPosed及Riru版本/Version of LSPosed及Riru版本 and Riru**

LSPosed: 1.5.2

Riru: 26.1.1

**核心破解版本/Version of Core Patch?**
version: 3.5

**相关日志/Related Logs**
[LSPosed_2021-08-27T10_47_39.450.zip](https://github.com/LSPosed/CorePatch/files/7065556/LSPosed_2021-08-27T10_47_39.450.zip)

Note: i have removed app list from log for privacy

**Comment by KarmaMod** [comment]
```
Performing Streamed Install
adb: failed to install xxxxxx.apk: Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.example.package attempting to redeclare permission com.example.package.permission.C2D_MESSAGE already owned by com.example.package]
```
What should i do?

**Comment by yujincheng08** [comment]
If 11, then it's caused by https://github.com/LSPosed/CorePatch/commit/65a3ee5245d42b0ac2348a32b074f298f359e295

**Comment by galenzhao** [comment]
Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package com.termux has a signing lineage that diverges from the lineage of the sharedUserId]

failed when install com.termux
with corepatch 3.7 on android 11

**Comment by eebssk1** [comment]
> Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package com.termux has a signing lineage that diverges from the lineage of the sharedUserId]
> 
> failed when install com.termux with corepatch 3.7 on android 11

Could you try the latest version from github action and enable the 'UsePreSig' switch.

**Comment by VanHoevenTR** [comment]
doesnt work for me too on Android 11

`adb: failed to install E:\Downloads\DISGAEA RPG_2.16.4_apkcombo.com_kill.apk: Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.boltrend.disgaea.en attempting to redeclare permission com.boltrend.disgaea.en.permission.C2D_MESSAGE already owned by com.boltrend.disgaea.en]`
