### ISSUE TITLE
[BUG] Color OS 12 can't install some apps with inconsistent signatures

### ISSUE THREAD

**Issue by NextAlone** [LSPosed/CorePatch#30]
**什么情况/What happened?**

无法安装部分签名冲突应用

**LSPosed及Riru版本/Version of LSPosed及Riru版本 and Riru**

LSPosed:1.61（6144）

Riru:26.1.2

**核心破解版本/Version of Core Patch?**
version:3.7

**相关日志/Related Logs**

Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.xfs.rootwords attempting to redeclare permission com.xfs.rootwords.openadsdk.permission.TT_PANGOLIN already owned by com.xfs.rootwords]

**Comment by eebssk1** [comment]
“始终使用已装app的签名” 这个选项也无效吗
