### ISSUE TITLE
[BUG] 更新到3.7后，所有app调用com.google.android.documentsui崩溃

### ISSUE THREAD

**Issue by o0HalfLife0o** [LSPosed/CorePatch#31]
**什么情况/What happened?**

如无法开机/模块无效等

比如magisk的安装本地模块功能调用com.google.android.documentsu时i崩溃，降级到3.4恢复正常

**LSPosed及Riru版本/Version of LSPosed及Riru版本 and Riru**

LSPosed:6148

Riru: 26.1.3

**核心破解版本/Version of Core Patch?**
version: 3.7

**相关日志/Related Logs**

**Comment by eebssk1** [comment]
有tombstone或者stacktrace或者相关日志吗

**Comment by o0HalfLife0o** [comment]
@eebssk1 请问应该怎么提取相关日志

**Comment by eebssk1** [comment]
看了下没有相关信息，应该不是native crash。请直接logcat时进行复现上传出现问题时的日志。此外xposed日志里也看看有没有相关信息

**Comment by Nronless** [comment]
> 看了下没有相关信息，应该不是native crash。请直接logcat时进行复现上传出现问题时的日志。此外xposed日志里也看看有没有相关信息

您好，我也遇到了和楼上一样的问题~这是我抓的崩溃日志，还请大佬有时间帮我看看。目前的现象就是，只要有edxposed，不管我有没有激活任何模块，只要有用到documentsui的地方都会直接闪退。

有点儿不太会用github，还麻烦您将就看：

https://github.com/Nronless/documentsui-/commit/75b5046d24040aaa47005ce7e1982ebeb693daf3#diff-36310716629fdaa7c898513a180bd11f79d97e779ca227f0adf0b337ad5bec34

**Comment by eebssk1** [comment]
> > 看了下没有相关信息，应该不是native crash。请直接logcat时进行复现上传出现问题时的日志。此外xposed日志里也看看有没有相关信息
> 
> 您好，我也遇到了和楼上一样的问题~这是我抓的崩溃日志，还请大佬有时间帮我看看。目前的现象就是，只要有edxposed，不管我有没有激活任何模块，只要有用到documentsui的地方都会直接闪退。
> 
> 有点儿不太会用github，还麻烦您将就看：
> 
> [Nronless/documentsui-@75b5046#diff-36310716629fdaa7c898513a180bd11f79d97e779ca227f0adf0b337ad5bec34](https://github.com/Nronless/documentsui-/commit/75b5046d24040aaa47005ce7e1982ebeb693daf3#diff-36310716629fdaa7c898513a180bd11f79d97e779ca227f0adf0b337ad5bec34)

你这个是启用了模块的日志吗?我看了一下是有hook的，如果没有启用任何模块仍然有相应问题的话请直接在框架repo里提issue

**Comment by Nronless** [comment]
> > > 看了下没有相关信息，应该不是native crash。请直接logcat时进行复现上传出现问题时的日志。此外xposed日志里也看看有没有相关信息
> > 
> > 
> > 您好，我也遇到了和楼上一样的问题~这是我抓的崩溃日志，还请大佬有时间帮我看看。目前的现象就是，只要有edxposed，不管我有没有激活任何模块，只要有用到documentsui的地方都会直接闪退。
> > 有点儿不太会用github，还麻烦您将就看：
> > [Nronless/documentsui-@75b5046#diff-36310716629fdaa7c898513a180bd11f79d97e779ca227f0adf0b337ad5bec34](https://github.com/Nronless/documentsui-/commit/75b5046d24040aaa47005ce7e1982ebeb693daf3#diff-36310716629fdaa7c898513a180bd11f79d97e779ca227f0adf0b337ad5bec34)
> 
> 你这个是启用了模块的日志吗?我看了一下是有hook的，如果没有启用任何模块仍然有相应问题的话请直接在框架repo里提issue

好的，感谢您的帮助！！！
