### ISSUE TITLE
[Feature request] Disable zipalign requirement

### ISSUE THREAD

**Issue by ghost** [LSPosed/CorePatch#41]
On Android 11, zipalign is a requirement in order to be able to install. If not, you will get parse error. This wa not a requirement on Android 10 and below. But i'm lazy to zipalign everytime I make changes to the APK especially if i'm just quick testing.

Is it possible to have an option to disable zipalign requirement?

**Comment by VanHoevenTR** [comment]
I think this would be great

**Comment by Young-Lord** [comment]
+1

**Comment by AndnixSH** [comment]
My Apktool GUI will auto zipalign once you sign the APK. Maybe it's not needed after all https://github.com/AndnixSH/APKToolGUI

**Comment by yujincheng08** [comment]
just algin ur apk
