### ISSUE TITLE
android9

### ISSUE THREAD

**Issue by scnjdx108** [LSPosed/CorePatch#53]
不打算支持android9了吗？

**Comment by EvatsugDnalloR** [comment]
> 不打算支持android9了吗？

好像旧版支持，可以一个个试一下

**Comment by AndnixSH** [comment]
Android 9 is no longer supported, however, you can use Core Patch 2.x https://mega.nz/folder/7EoyWSpC#2nkRRwUucCkUjlUO3PvSgA
