### ISSUE TITLE
[BUG] Android 12L july play system update break sign pass

### ISSUE THREAD

**Issue by duzhaokun123** [LSPosed/CorePatch#58]
**什么情况/What happened?**

install failed
```
INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package me.iacn.biliroaming signatures do not match previously installed version; ignoring!
```

**LSPosed及Riru版本/Version of LSPosed及Riru版本 and Riru**

LSPosed: 6596

Riru: none (zygisk)

**核心破解版本/Version of Core Patch?**
version: https://github.com/LSPosed/CorePatch/commit/e6bb66df45d66f3ede324674631b77e30a87814e

**相关日志/Related Logs**

[LSPosed_2022-08-12T12_30_12.103630.zip](https://github.com/LSPosed/CorePatch/files/9313680/LSPosed_2022-08-12T12_30_12.103630.zip)

**Comment by duzhaokun123** [comment]
bad solution:
```shell
pm uninstall com.google.android.art
```

**Comment by alberhazky** [comment]
OMG, thank you so much, I could not get it to work since July, you're a genius

**Comment by nutpantz** [comment]
> bad solution:
> 
> ```shell
> pm uninstall com.google.android.art
> ```
> 
> edit: you need rerun this after reinstall july play system update

I have play services disabled.

**Comment by alberhazky** [comment]
> > bad solution:
> > 
> > ```shell
> > pm uninstall com.google.android.art
> > ```
> > 
> > edit: you need rerun this after reinstall july play system update
> 
> I have play services disabled it has never updated. Just system updates.
> And i can't find com.google. Android. Art on my system

I can't find it on mine either but it's there because after running pm uninstall com.google.android.art and getting the success message on terminal, I reboot the phone and signature bypass works again, the only problem is whenever I let everything update on Google play store, it'll break again and not until I repeat the process it'll work again so, what package update is breaking this idk and where is com.google.android.art at idk either because if I knew I could have blocked it from automatically updating as a temporary solution

**Comment by nutpantz** [comment]
1|:/data/data/com.termux/files/home # pm uninstall >
Failure [DELETE_FAILED_INTERNAL_ERROR]

**Comment by yujincheng08** [comment]
Should have been fixed.

**Comment by ricardoabreujr** [comment]
> > > bad solution:
> > > ```shell
> > > pm uninstall com.google.android.art
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > edit: you need rerun this after reinstall july play system update
> > 
> > 
> > I have play services disabled it has never updated. Just system updates.
> > And i can't find com.google. Android. Art on my system
> 
> I can't find it on mine either but it's there because after running pm uninstall com.google.android.art and getting the success message on terminal, I reboot the phone and signature bypass works again, the only problem is whenever I let everything update on Google play store, it'll break again and not until I repeat the process it'll work again so, what package update is breaking this idk and where is com.google.android.art at idk either because if I knew I could have blocked it from automatically updating as a temporary solution

I'm having the same problem, the core patch doesn't work on my S20 Ultra. Running this "PM uninstall" code solves this problem? And then I can reinstall?
