### ISSUE TITLE
[BUG] not working on Android 12L

### ISSUE THREAD

**Issue by nutpantz** [LSPosed/CorePatch#61]
**什么情况/What happened?**
Failed to disable signature verification on pixel 6 Android 12L July update.

LSPosed Zygisk :1.83

**核心破解版本/Version of Core Patch?**
version:3.8

**Comment by AbdullahM0hamed** [comment]
https://github.com/LSPosed/CorePatch/issues/58#issuecomment-1221261414 worked for me on pixel 6 that I bought a few days ago

**Comment by nutpantz** [comment]
> [#58 (comment)](https://github.com/LSPosed/CorePatch/issues/58#issuecomment-1221261414) worked for me on pixel 6 that I bought a few days ago

What did you need to do to get it to work?
I had no errors on install that i saw, but it fails when i try to install an app with a different signature then the one that is installed.

**Comment by AbdullahM0hamed** [comment]
I ran the command `pm uninstall com.google.android.art` as root in termux

Then I rebooted

Then I reinstalled the CorePatch plugin and set it up

Then I rebooted

And it worked

**Comment by AbdullahM0hamed** [comment]
LMAO, my phone went ahead and re-installed the thing or whatever (on the previous reboot) and my phone started telling me packages conflict again, so I ran the command again and rebooted and it was once again fixed

Gonna have to figure out something more permanent

**Comment by AbdullahM0hamed** [comment]
OK now it longer works at all rip

**Comment by AbdullahM0hamed** [comment]
> OK now it longer works at all rip

Well, it is working again...

They are keeping me on my toes

**Comment by nutpantz** [comment]
Sounds like there is an issue.  I'll keep an eye on new developments

**Comment by wefalltomorrow** [comment]
Yup, not working here on A12L as well sadly.

**Comment by yujincheng08** [comment]
Duplicate of #58
