### ISSUE TITLE
[Bug] Cannot install apk without signature since Android 13

### ISSUE THREAD

**Issue by xiang473535976** [LSPosed/CorePatch#63]
### What happened/什么情况

安装核心破解3.9版本，无效  还是没法安装不通签名的系统应用 

### LSPosed version/LSPosed 版本

6633

### Android version/Android 版本

miui13  base on Android13

### Version of Core Patch/核心破解版本

3.9

### Logs/日志

[LSPosed_2022-10-25T15_08_55.838799.zip](https://github.com/LSPosed/CorePatch/files/9857971/LSPosed_2022-10-25T15_08_55.838799.zip)

**Comment by xiang473535976** [comment]
QQ:473535976

**Comment by xiang473535976** [comment]
![Screenshot_2022-10-25-16-10-47-554_com coderstory](https://user-images.githubusercontent.com/18111614/197721120-fee7fafb-e036-4e75-93e9-8b65cc583be0.jpg)
[services.zip](https://github.com/LSPosed/CorePatch/files/9858435/services.zip)

**Comment by xiang473535976** [comment]
@yujincheng08   谢谢   有需要可以加我qq

**Comment by yujincheng08** [comment]
adb 安装报什么错

**Comment by xiang473535976** [comment]
![Screenshot_2022-10-25-17-21-34-862_com miui packa](https://user-images.githubusercontent.com/18111614/197736041-15e464a4-a54a-4207-8578-21e6c09435d5.jpg)
@yujincheng08

**Comment by yujincheng08** [comment]
要 adb 安装的日志才知道具体错误

**Comment by xiang473535976** [comment]
@yujincheng08&nbsp; &nbsp;大佬 加个qq&nbsp; 473535976嘛&nbsp; 公司里&nbsp; &nbsp; &nbsp;github访问不是很方便




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LSPosed/CorePatch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 下午5:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LSPosed/CorePatch] [Bug] not support android 13 (Issue #63)





 
要 adb 安装的日志才知道具体错误

**Comment by xiang473535976** [comment]
![1666690080466](https://user-images.githubusercontent.com/18111614/197738099-0e8155ba-67ed-4088-84ee-5f5324d157a2.jpg)

**Comment by yujincheng08** [comment]
把 apk 放到内部存储空间，命名为 test.apk。打开任意一个终端，然后 `su`，然后 `pm install /sdcard/test.apk`，然后把报错发上来。

**Comment by yujincheng08** [comment]
> 把 apk 放到内部存储空间，命名为 test.apk。打开任意一个终端，然后 `su`，然后 `pm install /sdcard/test.apk`，然后把报错发上来。

按这个操作一波再抓日志

**Comment by duzhaokun123** [comment]
> 把 apk 放到内部存储空间，命名为 test.apk。打开任意一个终端，然后 `su`，然后 `pm install /sdcard/test.apk`，然后把报错发上来。

pm 不需要在 /data/local/tmp 吗

**Comment by xiang473535976** [comment]
@ @yujincheng08    还需要其他日志    ？？

**Comment by yujincheng08** [comment]
> 把 apk 放到内部存储空间，命名为 test.apk。打开任意一个终端，然后 `su`，然后 `pm install /sdcard/test.apk`，然后把报错发上来。

把 apk 放到内部存储空间，命名为 test.apk。打开任意一个终端，然后 su，然后 pm install /sdcard/test.apk，然后把报错发上来。

**Comment by yujincheng08** [comment]
> @ @yujincheng08 还需要其他日志 ？？

把 apk 放到内部存储空间，命名为 test.apk。打开任意一个终端，然后 su，然后 pm install /sdcard/test.apk，然后把报错发上来。

**Comment by xiang473535976** [comment]
![1](https://user-images.githubusercontent.com/18111614/197993858-0a021167-7a70-45b9-95b0-09a79c4eda18.jpg)
![Uploading 2.jpg…]()
@yujincheng08

**Comment by yujincheng08** [comment]
把 apk 放到 /data/local/tmp/ 下，命名为 test.apk。打开任意一个终端，然后 su，然后 pm install /data/local/tmp/test.apk，然后把报错发上来。

**Comment by yujincheng08** [comment]
@xiang473535976 再来按上面操作一波

**Comment by xiang473535976** [comment]
![Screenshot_2022-10-26-22-36-06-958_bin mt plus](https://user-images.githubusercontent.com/18111614/198056393-459c3617-98b9-40fe-92a0-9ffff5a91660.jpg)

大佬  加个口吧  方便交流点

**Comment by xiang473535976** [comment]
@yujincheng08   图片发了  大佬

**Comment by xiang473535976** [comment]
@yujincheng08   资料是否齐全了 大佬  在公司里   好弄点 谢谢 有需要可以加我qq473535976

**Comment by yujincheng08** [comment]
[Signed app bundle.zip](https://github.com/LSPosed/CorePatch/files/9875598/Signed.app.bundle.zip)
试试这个，如果不行发 LSPosed 日志。

**Comment by xiang473535976** [comment]
>
[LSPosed_2022-10-27T11_48_52.655598.zip](https://github.com/LSPosed/CorePatch/files/9875701/LSPosed_2022-10-27T11_48_52.655598.zip)
还是不行  大佬  安装后  重启了手机的

**Comment by xiang473535976** [comment]
@yujincheng08

**Comment by xiang473535976** [comment]
还是不行 大佬&nbsp; 安装你提供的新版本后




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LSPosed/CorePatch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月27日(星期四) 中午11:40
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [LSPosed/CorePatch] [Bug] not support android 13 (Issue #63)





 
Signed app bundle.zip
 试试这个，如果不行发 LSPosed 日志。

**Comment by coderstory** [comment]
直接删签名的情况好像没处理吧

**Comment by xiang473535976** [comment]
@coderstory  @yujincheng08  另一个大佬来了     希望越来越大了

**Comment by yujincheng08** [comment]
试试这个版本
[Signed app bundle.zip](https://github.com/LSPosed/CorePatch/files/9877802/Signed.app.bundle.zip)

**Comment by xiang473535976** [comment]
[LSPosed_2022-10-27T17_14_43.587896.zip](https://github.com/LSPosed/CorePatch/files/9877958/LSPosed_2022-10-27T17_14_43.587896.zip)
还是不行 @yujincheng08 @coderstory

**Comment by yujincheng08** [comment]
adb 安装时候报什么错

**Comment by xiang473535976** [comment]
![Screenshot_2022-10-27-17-21-31-090_bin mt plus](https://user-images.githubusercontent.com/18111614/198246292-08217549-29a4-4bbd-9c3d-defe08cfdd4a.jpg)
@yujincheng08

**Comment by yujincheng08** [comment]
把 apk 放到 /data/local/tmp/ 下，命名为 test.apk。打开任意一个终端，然后 su，然后 pm install /data/local/tmp/test.apk，然后把报错发上来。

**Comment by xiang473535976** [comment]
![Screenshot_2022-10-27-17-24-29-739_bin mt plus](https://user-images.githubusercontent.com/18111614/198246779-10d30b4f-771e-4271-98e3-b8da0d3ac126.jpg)
@yujincheng08

**Comment by yujincheng08** [comment]
试试这个
[Signed app bundle.zip](https://github.com/LSPosed/CorePatch/files/9878114/Signed.app.bundle.zip)


另外把你 APK 发上来。

**Comment by xiang473535976** [comment]
[堆叠桌面1.8不开启强制模糊.zip](https://github.com/LSPosed/CorePatch/files/9878148/1.8.zip)
@yujincheng08

**Comment by xiang473535976** [comment]
@yujincheng08 @coderstory   谢谢大佬  最新版本行了  安装成功  安卓13

**Comment by yujincheng08** [comment]
[Signed app bundle.zip](https://github.com/LSPosed/CorePatch/files/9878285/Signed.app.bundle.zip)
再试试这个

**Comment by xiang473535976** [comment]
@yujincheng08   成功了 你最后发的这个也能安装了
