### ISSUE TITLE
[Bug] 安卓12，4.0核心破解失效

### ISSUE THREAD

**Issue by niu164** [LSPosed/CorePatch#67]
### What happened/什么情况

安装4.0 核心破解后，安装软件提示
INSTALL_FAILED_DUPLATE_PERMISSION: Package com.miui.home attempting to redeclare permission com.miui.home.launcher.permission.PUSH_REFRESH_WIDGET already owned by com.miui.home
回退到3.8版本正常

### LSPosed version/LSPosed 版本

6609

### Android version/Android 版本

12

### Version of Core Patch/核心破解版本

4.0

### Logs/日志

[LSPosed_2022-10-30T00_56_12.932.zip](https://github.com/LSPosed/CorePatch/files/9894189/LSPosed_2022-10-30T00_56_12.932.zip)

**Comment by yujincheng08** [comment]
先复现一次问题再发日志？

**Comment by niu164** [comment]
> 先复现一次问题再发日志？

[LSPosed_2022-10-30T11_01_28.471.zip](https://github.com/LSPosed/CorePatch/files/9894983/LSPosed_2022-10-30T11_01_28.471.zip)
来了

**Comment by yujincheng08** [comment]
用这个版本复现一次再发日志

[app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895090/app-debug.zip)

**Comment by niu164** [comment]
> 用这个版本复现一次再发日志
> 
> [app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895090/app-debug.zip)

[Uploading LSPosed_2022-10-30T12_41_55.090.zip…]()
来了

**Comment by niu164** [comment]
> 用这个版本复现一次再发日志
> 
> [app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895090/app-debug.zip)

[LSPosed_2022-10-30T12_41_55.090.zip](https://github.com/LSPosed/CorePatch/files/9895103/LSPosed_2022-10-30T12_41_55.090.zip)

**Comment by yujincheng08** [comment]
apk 发一下

**Comment by niu164** [comment]
> apk 发一下

https://wwf.lanzoue.com/iK3340erp43e
密码  ft32

**Comment by yujincheng08** [comment]
我这里无法复现，能成功安装

**Comment by yujincheng08** [comment]
3.9 是否有问题？

**Comment by niu164** [comment]
> 我这里无法复现，能成功安装

4.0我开启那个设置里面下面两个，能成功安装，但是无限闪退，不开安不上，3.8不开就能安装而且正常使用，我试试3.9去

**Comment by yujincheng08** [comment]
你不是说不能安装吗。。

**Comment by yujincheng08** [comment]
开启那个设置能安装就代表没问题。

**Comment by niu164** [comment]
> 你不是说不能安装吗。。

😂我以前用的时候没开过那两个开关，试的时候开了，3.9不开两个开关，正常安装使用

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895212/app-debug.zip)
试试这个版本

**Comment by niu164** [comment]
> [app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895212/app-debug.zip) 试试这个版本

INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.miui.home attempting to redeclare permission com.miui.home.launcher.permission.PUSH_REFRESH_WIDGET already owned by com.miui.home
还是这个

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895250/app-debug.zip)
试试这个版本

**Comment by niu164** [comment]
> [app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895250/app-debug.zip) 试试这个版本

正常了，可以安装，不会闪退，但是这不是3.9嘛😂

**Comment by yujincheng08** [comment]
我在确定哪个提交出问题。。

[app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895272/app-debug.zip)
试试这个

**Comment by niu164** [comment]
> 我在确定哪个提交出问题。。
> 
> [app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895272/app-debug.zip) 试试这个

可以正常安装使用，不闪退

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895568/app-debug.zip)
试试这个

**Comment by niu164** [comment]
> [app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895568/app-debug.zip) 试试这个

这个装不上，提示

创建 Session...
创建会话...
会话ID:1406225511
打开会话...
打开 Session...
读取中... Yes Apk
结束 Session...
安装状态: 4 (INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl1406225511.tmp/0.apk: Failed to collect certificates from /data/app/vmdl1406225511.tmp/0.apk: META-INF/PLATFORM.SF indicates /data/app/vmdl1406225511.tmp/0.apk is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?)
!: content://bin.mt.plus.fp/MT/APK_FOR_INSTALLATION.apk
错误: 
java.lang.NullPointerException: Parameter specified as non-null is null: method com.yxer.packageinstalles.core.installer.apks.root.apksRoot.ԫ, parameter <set-?>
java.lang.NullPointerException: Parameter specified as non-null is null: method com.yxer.packageinstalles.core.installer.apks.root.apksRoot.ԫ, parameter <set-?>
	at ჽ.Ԩ.Ԩ(Unknown Source:2)
	at com.yxer.packageinstalles.core.installer.apks.root.apksRoot.ԫ(SourceFile:106)
	at com.yxer.packageinstalles.core.installer.apks.root.apksRoot.Ԭ(SourceFile:7)
	at com.yxer.packageinstalles.core.installer.apks.root.apksRoot.main(SourceFile:3)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
错误：31 
Attempt to invoke virtual method 'java.lang.String ჽ.Ԩ.toString()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String ჽ.Ԩ.toString()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String ჽ.Ԩ.toString()' on a null object reference
	at com.yxer.packageinstalles.core.installer.apks.root.apksRoot.Ԭ(SourceFile:8)
	at com.yxer.packageinstalles.core.installer.apks.root.apksRoot.main(SourceFile:3)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)

**Comment by yujincheng08** [comment]
发 LSPosed 日志

**Comment by niu164** [comment]
> 发 LSPosed 日志

[LSPosed_2022-10-30T18_15_44.646.zip](https://github.com/LSPosed/CorePatch/files/9895582/LSPosed_2022-10-30T18_15_44.646.zip)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895586/app-debug.zip)
试试这个

**Comment by niu164** [comment]
> [app-debug.zip](https://github.com/LSPosed/CorePatch/files/9895586/app-debug.zip) 试试这个

可以安装了，正常使用没有闪退，还是提供下日志吧
[LSPosed_2022-10-30T18_24_10.197.zip](https://github.com/LSPosed/CorePatch/files/9895598/LSPosed_2022-10-30T18_24_10.197.zip)
