### ISSUE TITLE
[Bug] can't find link for branch q

### ISSUE THREAD

**Issue by nutpantz** [LSPosed/CorePatch#68]
### What happened/什么情况

Can't find the link for branchq 

### LSPosed version/LSPosed 版本

1.82

### Android version/Android 版本

9

### Version of Core Patch/核心破解版本

4

### Logs/日志

The Readme.md  specifies branch Q for Android 9
But there is no release link anywhere.

Link "You can download history version from https://soft.shouji.com.cn/down/32512.html" appears dead

I would ask in telegram but i don't have a phone number to register with.

**Comment by yujincheng08** [comment]
its not

**Comment by duzhaokun123** [comment]
keeping the link to "手机助手" website should be considered dev's negligence

**Comment by AndnixSH** [comment]
Try my build, it has Android 9 support 

https://github.com/AndnixSH/CorePatch/releases
