### ISSUE TITLE
[Bug]  A13app降级安装失败

### ISSUE THREAD

**Issue by 1human** [LSPosed/CorePatch#69]
### What happened/什么情况

A13app降级安装失败
模块无效

### LSPosed version/LSPosed 版本

1.8.4 6641 zygisk

### Android version/Android 版本

Andoid13 nusantararom

### Version of Core Patch/核心破解版本

4.1

### Logs/日志

Command: pm install-commit 840244051
Exit code: 1
Out:
Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package cn.kuwo.kwmusichd attempting to redeclare permission cn.kuwo.kwmusichd.signatureOrSystem already owned by cn.kuwo.kwmusichd]
=============
Err:

[LSPosed_2022-11-01T10_00_43.652451.zip](https://github.com/LSPosed/CorePatch/files/9906118/LSPosed_2022-11-01T10_00_43.652451.zip)

**Comment by yujincheng08** [comment]
设置问题。
