### ISSUE TITLE
[Bug] Can't install apps with different signatures

### ISSUE THREAD

**Issue by enskye** [LSPosed/CorePatch#72]
### What happened/什么情况

Can't install apps with different signatures

### LSPosed version/LSPosed 版本

6656

### Android version/Android 版本

13

### Version of Core Patch/核心破解版本

4.2

### Logs/日志

[LSPosed_2022-11-26T18_47_39.203977.zip](https://github.com/LSPosed/CorePatch/files/10096665/LSPosed_2022-11-26T18_47_39.203977.zip)

### Module settings screenshot/模块设置截图

![Screenshot_20221126-185312](https://user-images.githubusercontent.com/62252655/204099998-e9d4fd1e-bf60-4ee0-b9b7-84c2d85d2a47.png)

**Comment by yujincheng08** [comment]
I don't have pixel 7 and thus I won't bother this issue until my device can reproduce or I have the mod to bother this.

**Comment by yujincheng08** [comment]
btw, you should at least show the error message when you install from commandline.

also, have a test on LSPosed 6650.

**Comment by pseudoparenchymatous** [comment]
Same problem with me on Android 13. Downgrading works perfect 👌. But install with different signature doesn't work. BTW, where to find build 6650? It's only 6649 on `Releases`

**Comment by JimmyJones97** [comment]
Facing the same issue on Android 11 (Pixel 3xl), Play services update maybe ?

`adb: failed to install test.apk: Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.garena.game.kgvn attempting to redeclare permission com.garena.game.kgvn.permission.PUSH_NOTIFICATION_TOKEN_UPDATE already owned by com.garena.game.kgvn]`

Let me know if you need any specific debug info.

**Comment by yujincheng08** [comment]
close because there was no response to my request.

**Comment by pseudoparenchymatous** [comment]
I see people filing issues that it doesn't work for A13 and you close with no answer. Just say its for A12 and below only. No need to lie 😂

**Comment by yujincheng08** [comment]
@pseudoparenchymatous it works at least on my A13 devices :)

**Comment by yujincheng08** [comment]
And `INSTALL_FAILED_DUPLICATE_PERMISSION` problem was almost because of configuration. I don't have to lie. I can only give up this project if you think I am lying.

**Comment by enskye** [comment]
seems like problem was caused by lsposed. no issues with LSPosed 6662.

**Comment by JimmyJones97** [comment]
> seems like problem was caused by lsposed. no issues with LSPosed <6661

The issue you posted was with 6656 that is < 6661

This issue persists with 6664.
