### ISSUE TITLE
[Bug] Module does not upgrade or downgrade some apps with different signatures. 

### ISSUE THREAD

**Issue by Kerrythesquirrelsquid** [LSPosed/CorePatch#73]
### What happened/什么情况

Module does not downgrade some apps with different signatures. Module does not update some apps with different signatures. 

### LSPosed version/LSPosed 版本

1.8.5(6649) Zygisk

### Android version/Android 版本

12

### Version of Core Patch/核心破解版本

4.2

### Logs/日志

[LSPosed_2023-01-13T17_32_40.930773.zip](https://github.com/LSPosed/CorePatch/files/10416062/LSPosed_2023-01-13T17_32_40.930773.zip)
[LSPosed_2023-01-13T17_32_34.495689.zip](https://github.com/LSPosed/CorePatch/files/10416063/LSPosed_2023-01-13T17_32_34.495689.zip)
[LSPosed_2023-01-13T16_44_41.413235.zip](https://github.com/LSPosed/CorePatch/files/10416064/LSPosed_2023-01-13T16_44_41.413235.zip)
[hma_logs_2023-01-12_12.21.31.log](https://github.com/LSPosed/CorePatch/files/10416065/hma_logs_2023-01-12_12.21.31.log)

### Module settings screenshot/模块设置截图

![Screenshot_20230113-171819](https://user-images.githubusercontent.com/122650584/212438014-116695e6-79a9-4a2b-87d7-d559680f1482.png)

**Comment by klxiaoniu** [comment]
I met the same problem. MIUI 14, android 13
安装失败 -112
该安装包与您的系统不兼容

**Comment by bzz11g** [comment]
Me too Pixel 6 Android 13 build TQ1A.230105.002

**Comment by qstdnx** [comment]
same problem,
A12 miui13
![Screenshot_2023-01-29-14-27-26-316_com miui packageinstaller](https://user-images.githubusercontent.com/20844622/215309205-05ef36f7-d7d4-49a8-a432-2e0888af58c7.jpg)

用爱玩机工具箱安装器显示
操作异常！(1)

STDOUT
数据初始化中！
Keep_v7.43.1安装应用失败！

STDERR
Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.gotokeep.keep attempting to redeclare permission com.gotokeep.keep.permission.MIPUSH_RECEIVE already owned by com.gotokeep.keep]
错误识别码：1

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/220628726-3ebf12db-fd97-4e19-9232-c0b04afbb058.png)
You should turn this on temporarily for this kind of installation.

**Comment by lord-ne** [comment]
This was closed as not planned, but I think it was actually added in https://github.com/LSPosed/CorePatch/commit/02cbc1e8858016cefadb179af2c7500b6a30cac9?
