### ISSUE TITLE
[Bug] signatures are inconsistent

### ISSUE THREAD

**Issue by yifan18** [LSPosed/CorePatch#74]
### What happened/什么情况

I use the command "adb install-multiple <base.apk> <obbasset.apk>" to install xapk file, it shows errors below.
```
PS C:\Users\Administrator\Downloads\Code\test> adb install-multiple 'c:\Users\Administrator\Downloads\dump-tools\APK Easy Tool v1.60 Portable\2-Recompiled APKs\com.xxx.xxx.apk' c:\Users\Administrator\Downloads\dump-apks\obbassets.apk
adb: failed to finalize session
Failure [INSTALL_FAILED_INVALID_APK: /data/app/vmdl209750275.tmp/obbassets.apk signatures are inconsistent]
``` 
both base.apk and obbasset.apk has stamp-cert-sha256 in their root folder, maybe it's the reason caused this problem

```
adb --version
Android Debug Bridge version 1.0.41
Version 33.0.3-8952118
```
by the way, i've tried latest version LSPosed 1.8.6 with CorePatch 4.2, it has the same problem

### LSPosed version/LSPosed 版本

6552-zygisk-release

### Android version/Android 版本

10

### Version of Core Patch/核心破解版本

3.5

### Logs/日志

didn't show any log in both Modules Logs and Verbose Logs of LSPosed

### Module settings screenshot/模块设置截图

![Screenshot_20230121-213722](https://user-images.githubusercontent.com/6284047/213869647-b9faa663-0d10-4a72-87e3-c9e5e61a1d44.png)

**Comment by yujincheng08** [comment]
Make sure the two apks are signed in the same signature. If not, you can sign them yourselves.
