### ISSUE TITLE
安卓13，无法覆盖安装签名不一样的安装包

### ISSUE THREAD

**Issue by niu164** [LSPosed/CorePatch#76]
### What happened/什么情况

安装应用，由于签名不同无法覆盖安装
INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.paget96.batteryguru attempting to redeclare permission com.paget96.batteryguru.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION already owned by com.paget96.batteryguru

INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package com.mxtech.videoplayer.ad has a signing lineage that diverges from the lineage of the sharedUserId
试了两个安装包是两个不同的报错
模块设置全开

### LSPosed version/LSPosed 版本

框架版本 1.8.6 (6712)  管理器版本 1.8.6 (6712)

### Android version/Android 版本

13 (API 33) 

### Version of Core Patch/核心破解版本

4.2

### Logs/日志

[LSPosed_2023-04-01T11_32_25.645489.zip](https://github.com/LSPosed/CorePatch/files/11128382/LSPosed_2023-04-01T11_32_25.645489.zip)

### Module settings screenshot/模块设置截图

![Screenshot_2023-04-01-11-40-34-445_com coderstory toolkit](https://user-images.githubusercontent.com/76257039/229263999-569f3719-2ec4-48b2-96f7-8f28ef7a0015.jpg)

**Comment by Rilomilo** [comment]
另外核心破解也不能绕过含有share_uid的应用，会提示INSTALL_FAILED_SHARED_USER_INCOMPATIBLE，希望模块能够支持share_uid破解

**Comment by niu164** [comment]
![Screenshot_2023-08-27-02-09-51-816_com.rosan.installer.x.jpg](https://github.com/LSPosed/CorePatch/assets/76257039/da8284c2-62d4-4099-b581-b96c58cb90b0)

补充

![Screenshot_2023-08-27-02-09-51-816_com.rosan.installer.x.jpg](https://github.com/LSPosed/CorePatch/assets/76257039/fc61be61-1f90-4ce2-8f62-b45ce8a45c61)

这该如何解决？

**Comment by Howard20181** [comment]
Fixed by 02cbc1e8858016cefadb179af2c7500b6a30cac9
