### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by Dyingchen** [LSPosed/CorePatch#79]
### What happened/什么情况

没有以前版本的源码了吗 正在学习安卓7的源码 想要学习一下2.x的内部实现

### LSPosed version/LSPosed 版本

0.1

### Android version/Android 版本

7.1.2

### Version of Core Patch/核心破解版本

2.0

### Logs/日志

/

### Module settings screenshot/模块设置截图

/

**Comment by coderstory** [comment]
master分支不是有嘛

**Comment by Jesse205** [comment]
> master分支不是有嘛

你好，请问其他分支在哪里？我只能看到main分支，没有master以及其他分支
![Screenshot_2024-02-11-07-00-13-015_com.github.android.jpg](https://github.com/LSPosed/CorePatch/assets/51242302/00d2c495-1568-4b69-93a3-1e263bf44552)
