### ISSUE TITLE
Disable Signature verification doesn't works on android 10.

### ISSUE THREAD

**Issue by UniverseCodex01** [LSPosed/CorePatch#98]
### What happened/什么情况

I'm trying to install Kiwi browser GitHub release over Play Store release but I get installation error due to different signatures.

### LSPosed version/LSPosed 版本

1.9.2 (7024)

### Android version/Android 版本

10

### Version of Core Patch/核心破解版本

4.3 

### Logs/日志

[LSPosed_2023-11-29T22_18_31.716.zip](https://github.com/LSPosed/CorePatch/files/13507176/LSPosed_2023-11-29T22_18_31.716.zip)

### Module settings screenshot/模块设置截图

![Screenshot_2023-11-29-22-18-45-199_com coderstory toolkit](https://github.com/LSPosed/CorePatch/assets/93066706/020f1ef6-b6cc-4d80-a097-036a8b3463d7)

**Comment by Howard20181** [comment]
Unable to reproduce, no useful information in logs
Please try again with an updated version from Actions
For feedback, please upload different packages before and after installation for testing.
